src/Entity/Driver.php
<?php

namespace App\Entity;

/**
 * Driver
 */
class Driver
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $name;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $blades;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $weaponLevels;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->blades = new \Doctrine\Common\Collections\ArrayCollection();
        $this->weaponLevels = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return Driver
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Add blade.
     *
     * @param \App\Entity\Blade $blade
     *
     * @return Driver
     */
    public function addBlade(\App\Entity\Blade $blade)
    {
        $this->blades[] = $blade;

        return $this;
    }

    /**
     * Remove blade.
     *
     * @param \App\Entity\Blade $blade
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeBlade(\App\Entity\Blade $blade)
    {
        return $this->blades->removeElement($blade);
    }

    /**
     * Get blades.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getBlades()
    {
        return $this->blades;
    }

    /**
     * Add weaponLevel.
     *
     * @param \App\Entity\WeaponLevel $weaponLevel
     *
     * @return Driver
     */
    public function addWeaponLevel(\App\Entity\WeaponLevel $weaponLevel)
    {
        $this->weaponLevels[] = $weaponLevel;

        return $this;
    }

    /**
     * Remove weaponLevel.
     *
     * @param \App\Entity\WeaponLevel $weaponLevel
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeWeaponLevel(\App\Entity\WeaponLevel $weaponLevel)
    {
        return $this->weaponLevels->removeElement($weaponLevel);
    }

    /**
     * Get weaponLevels.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getWeaponLevels()
    {
        return $this->weaponLevels;
    }
}

src/Entity/SkillLevel.php
<?php

namespace App\Entity;

/**
 * SkillLevel
 */
class SkillLevel
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var int
     */
    private $level;

    /**
     * @var \App\Entity\Blade
     */
    private $blade;

    /**
     * @var \App\Entity\Skill
     */
    private $skill;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set level.
     *
     * @param int $level
     *
     * @return SkillLevel
     */
    public function setLevel($level)
    {
        $this->level = $level;

        return $this;
    }

    /**
     * Get level.
     *
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     * Set blade.
     *
     * @param \App\Entity\Blade|null $blade
     *
     * @return SkillLevel
     */
    public function setBlade(\App\Entity\Blade $blade = null)
    {
        $this->blade = $blade;

        return $this;
    }

    /**
     * Get blade.
     *
     * @return \App\Entity\Blade|null
     */
    public function getBlade()
    {
        return $this->blade;
    }

    /**
     * Set skill.
     *
     * @param \App\Entity\Skill|null $skill
     *
     * @return SkillLevel
     */
    public function setSkill(\App\Entity\Skill $skill = null)
    {
        $skill->addBlade($this);
        $this->skill = $skill;

        return $this;
    }

    /**
     * Get skill.
     *
     * @return \App\Entity\Skill|null
     */
    public function getSkill()
    {
        return $this->skill;
    }

    public function getName()
    {
        return $this->skill->getName();
    }
}

src/Entity/WeaponLevel.php
<?php

namespace App\Entity;

/**
 * WeaponLevel
 */
class WeaponLevel
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var int
     */
    private $x = 1;

    /**
     * @var int
     */
    private $y = 1;

    /**
     * @var int
     */
    private $b = 1;

    /**
     * @var int
     */
    private $chain = 1;

    /**
     * @var \App\Entity\Driver
     */
    private $driver;

    /**
     * @var \App\Entity\Weapon
     */
    private $weapon;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set x.
     *
     * @param int $x
     *
     * @return WeaponLevel
     */
    public function setX($x)
    {
        $this->x = $x;

        return $this;
    }

    /**
     * Get x.
     *
     * @return int
     */
    public function getX()
    {
        return $this->x;
    }

    /**
     * Set y.
     *
     * @param int $y
     *
     * @return WeaponLevel
     */
    public function setY($y)
    {
        $this->y = $y;

        return $this;
    }

    /**
     * Get y.
     *
     * @return int
     */
    public function getY()
    {
        return $this->y;
    }

    /**
     * Set b.
     *
     * @param int $b
     *
     * @return WeaponLevel
     */
    public function setB($b)
    {
        $this->b = $b;

        return $this;
    }

    /**
     * Get b.
     *
     * @return int
     */
    public function getB()
    {
        return $this->b;
    }

    /**
     * Set chain.
     *
     * @param int $chain
     *
     * @return WeaponLevel
     */
    public function setChain($chain)
    {
        $this->chain = $chain;

        return $this;
    }

    /**
     * Get chain.
     *
     * @return int
     */
    public function getChain()
    {
        return $this->chain;
    }

    /**
     * Set driver.
     *
     * @param \App\Entity\Driver|null $driver
     *
     * @return WeaponLevel
     */
    public function setDriver(\App\Entity\Driver $driver = null)
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * Get driver.
     *
     * @return \App\Entity\Driver|null
     */
    public function getDriver()
    {
        return $this->driver;
    }

    /**
     * Set weapon.
     *
     * @param \App\Entity\Weapon|null $weapon
     *
     * @return WeaponLevel
     */
    public function setWeapon(\App\Entity\Weapon $weapon = null)
    {
        $this->weapon = $weapon;

        return $this;
    }

    /**
     * Get weapon.
     *
     * @return \App\Entity\Weapon|null
     */
    public function getWeapon()
    {
        return $this->weapon;
    }

    public function getName()
    {
        return $this->weapon->getName();
    }

    public function getArts()
    {
        return array(
            'x'     => $this->getX(),
            'y'     => $this->getY(),
            'b'     => $this->getB(),
            'chain' => $this->getCHain(),
        );
    }

    public function setArt($item, $level)
    {
        switch ($item) {
            case 'x':
                $this->setX($level);
                break;
            case 'y':
                $this->setY($level);
                break;
            case 'b':
                $this->setB($level);
                break;
            case 'chain':
                $this->setChain($level);
                break;
        }

        return $this;
    }
}

src/Form/DriverType.php
<?php

namespace App\Form;

use App\Entity\Driver;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DriverType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', null, array(
                'label_format' => 'driver.fields.%name%',
            ))
            ->add('blades', \Symfony\Component\Form\Extension\Core\Type\CollectionType::class, array(
                'entry_type'    => BladeType::class,
                'prototype'     => true,
                'allow_add'     => true,
                'allow_delete'  => true,
                'by_reference'  => false,
                'entry_options' => array(
                    'label' => false,
                ),
                'label_format' => 'driver.fields.%name%',
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Driver::class,
        ]);
    }
}

src/Controller/DriverController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\Driver;
use Symfony\Component\HttpFoundation\Request;
use App\Form\DriverType;

class DriverController extends Controller
{
    public function index(Request $request)
    {
        $drivers = $this->getDoctrine()->getManager()->getRepository(Driver::class)->findAll();
        return $this->render('driver/index.html.twig', [
            'drivers' => $drivers,
        ]);
    }

    public function new(Request $request)
    {
        $driver = new Driver();
        $form = $this->createForm(DriverType::class, $driver);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($driver);
            $em->flush();

            $this->addFlash('success', $this->get('translator')->trans('driver.success.created', array('%name%' => $driver->getName()), 'flash'));
            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/new.html.twig', array(
            'driver' => $driver,
            'form' => $form->createView(),
        ));
    }

    public function show(Driver $driver, Request $request)
    {
        return $this->render('driver/show.html.twig', array(
            'driver' => $driver,
            'delete_form' => $this->createDeleteForm($driver)->createView(),
        ));
    }

    public function edit(Driver $driver, Request $request)
    {
        $form = $this->createForm(DriverType::class, $driver);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($driver);
            $em->flush();

            $this->addFlash('success', $this->get('translator')->trans('driver.success.edited', array('%name%' => $driver->getName()), 'flash'));
            return $this->redirectToRoute('driver_index');
        }

        return $this->render('driver/edit.html.twig', array(
            'driver' => $driver,
            'form' => $form->createView(),
            'delete_form' => $this->createDeleteForm($driver)->createView(),
        ));
    }

    private function createDeleteForm(Driver $driver)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('driver_delete', array('id' => $driver->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

    public function delete(Driver $driver, Request $request)
    {
        $form = $this->createDeleteForm($driver);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($driver);
            $em->flush();
            $this->addFlash('success', $this->get('translator')->trans('driver.success.deleted', array(), 'flash'));
        } else {
            $this->addFlash('success', $this->get('translator')->trans('driver.error.deleted', array(), 'flash'));
        }

        return $this->redirectToRoute('driver_index');
    }
}

templates/driver/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ driver.name }} | {{ parent() }}{% endblock %}

{% block body %}
	<h2>{{ driver.name }}</h2>

	{% include 'driver/form.html.twig' with {'form': form} %}

	<ul class="list-inline float-right">
		<li class="list-inline-item">
			<a href="{{ path('driver_index') }}" class="btn btn-light"><i class="fa fa-list"></i></a>
		</li>
		<li class="list-inline-item">
			{{ form_start(delete_form) }}
				<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
			{{ form_end(delete_form) }}
		</li>
	</ul>
{% endblock %}

{% block javascripts %}
		<script src="{{ asset('js/collection_adder.js') }}"></script>
{% endblock %}

templates/driver/form.html.twig
{{ form_start(form) }}
	{{ form_widget(form) }}
	<button type="submit" class="btn btn-primary float-left"><i class="fa fa-check"></i></button>
{{ form_end(form) }}

templates/driver/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'driver.index.title'|trans }} | {{ parent() }}{% endblock %}

{% block body %}
	<h2>{{ 'driver.index.heading'|trans }}</h2>

	<table class="table table-sm table-hover">
		<thead>
			<tr>
				<th>{{ 'driver.fields.name'|trans }}</th>
				<th>{{ 'driver.fields.blades'|trans }}</th>
				<th><a href="{{ path('driver_new') }}" class="btn btn-sm btn-success"><i class="fa fa-plus-circle"></i></a></th>
			</tr>
		</thead>
		<tbody>
		{% for driver in drivers %}
			<tr>
				<td>{{ driver.name }}</td>
				<td>{{ driver.blades|length }}</td>
				<td><a href="{{ path('driver_show', { 'id': driver.id }) }}" class="btn btn-sm btn-outline-info"><i class="fa fa-eye"></i></a>
					<a href="{{ path('driver_edit', { 'id': driver.id }) }}" class="btn btn-sm btn-outline-warning"><i class="fa fa-pencil"></i></a></td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/driver/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'driver.new.title'|trans }} | {{ parent() }}{% endblock %}

{% block body %}
	<h2>{{ 'driver.new.heading'|trans }}</h2>

	{% include 'driver/form.html.twig' with {'form': form} %}

	<ul class="list-inline float-right">
		<li class="list-inline-item">
			<a href="{{ path('driver_index') }}" class="btn btn-light"><i class="fa fa-list"></i></a>
		</li>
	</ul>
{% endblock %}

{% block javascripts %}
		<script src="{{ asset('js/collection_adder.js') }}"></script>
{% endblock %}

templates/driver/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ driver.name }} | {{ parent() }}{% endblock %}

{% block body %}
	<h2>{{ driver.name }}</h2>

	<table class="table table-sm">
		<tbody>
			<tr>
				<th colspan="4"><h3>{{ 'driver.fields.blades'|trans }} <small>({{ driver.blades.count }})</h3></th>
			</tr>
			{% for blade in driver.blades %}
			<tr style="background-color: {{ blade.element.color }}">
				<td>{{ blade.name }}</td>
				<td>{{ blade.weapon.name }}</td>
				<td>{% for i in 1..(blade.rareness) %}{% if i is odd %}<sup>{% else %}<sub>{% endif %}👑{% if i is odd %}</sup>{% else %}</sub>{% endif %}{% endfor %}</td>
				<td><a href="{{ path('blade_show', { 'id': blade.id }) }}" class="btn btn-sm btn-info"><i class="fa fa-eye"></i></a>
					<div class="btn-group">
						<div class="btn-group dropleft">
							<button type="button" class="btn btn-sm btn-warning dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
							<table class="dropdown-menu">
								<thead>
									<tr>
										<th></th>
										<th>{{ 'blade.fields.trustLevel'|trans }}</th>
										<th id="TL{{ blade.id }}">{{ ('blade.trustLevels.' ~ blade.trustLevel)|trans }}</th>
										<th>{% if blade.trustLevel < 6 -%}
											<a href="{{ path('blade_trust', { 'id': blade.id }) }}" class="btn btn-sm btn-outline-success ajaxify" data-load-target="#TL{{ blade.id }}"><i class="fa fa-chevron-circle-up"></i></a></td>
											{%- endif %}</th>
									</tr>
								</thead>
								<tbody>
								{% for skill in blade.skills %}
									<tr>
										<td>
											{% if skill.level > 1 -%}
											<a href="{{ path('skill_change', { 'id': skill.id, 'change': -1 }) }}" class="btn btn-sm btn-outline-warning ajaxify" data-load-target="#S{{ skill.id }}"><i class="fa fa-chevron-circle-down"></i></a>
											{% endif -%}
										</td>
										<td>{{ skill.name|default('Non chargé') }}</td>
										<td id="S{{ skill.id }}">{{ skill.level }}</td>
										<td><a href="{{ path('skill_change', { 'id': skill.id, 'change': 1 }) }}" class="btn btn-sm btn-outline-success ajaxify" data-load-target="#S{{ skill.id }}"><i class="fa fa-chevron-circle-up"></i></a></td>
									</tr>
								{% endfor %}
								</tbody>
							</table>
						</div>
						<a href="{{ path('blade_edit', { 'id': blade.id }) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
					</div></td>
			</tr>
			{% endfor %}
			<tr>
				<th colspan="4"><h3>{{ 'driver.fields.weaponLevels'|trans }} <small>({{ driver.weaponLevels.count }})</h3></th>
			</tr>
			{% for weapon in driver.weaponLevels %}
			<tr>
				<th>{{ weapon.name }}</th>
				{% for item,art in weapon.arts %}
				<td>{{ ('weapon_level.fields.' ~ item)|trans }}</td>
				<td id="L{{ item ~ weapon.id }}">{{ art }}</td>
				<td><a href="{{ path('weapon_change', { 'id': weapon.id, 'item': item, 'change': 1 }) }}" class="btn btn-sm btn-outline-success ajaxify" data-load-target="#L{{ item ~ weapon.id }}"><i class="fa fa-chevron-circle-up"></i></a>
					<a href="{{ path('weapon_change', { 'id': weapon.id, 'item': item, 'change': -1 }) }}" class="btn btn-sm btn-outline-warning ajaxify" data-load-target="#L{{ item ~ weapon.id }}"><i class="fa fa-chevron-circle-down"></i></a></td>
				{%- if not loop.last %}
			</tr>
			<tr>
				<td></td>
				{%- endif -%}
				{% endfor %}
			</tr>
			{% endfor %}
		</tbody>
	</table>

	<ul class="list-inline float-right">
		<li class="list-inline-item">
			<a href="{{ path('driver_index') }}" class="btn btn-light"><i class="fa fa-list"></i></a>
		</li>
		<li class="list-inline-item">
			<a href="{{ path('driver_edit', { 'id': driver.id }) }}" class="btn btn-warning" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
		</li>
		<li class="list-inline-item">
			{{ form_start(delete_form) }}
				<button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
			{{ form_end(delete_form) }}
		</li>
	</ul>
{% endblock %}

{% block javascripts %}
		<script src="{{ asset('js/ajaxify.js') }}"></script>
{% endblock %}